# Generated by Django 5.1.1 on 2024-10-15 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_account_first_name_remove_account_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
