# Generated by Django 5.1.1 on 2024-10-16 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_courses'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course',
        ),
    ]
