# Generated by Django 5.1.1 on 2024-10-18 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_account_phone'),
        ('api', '0004_rename_courses_course'),
    ]

    operations = [
    ]
