# Generated by Django 5.1.1 on 2024-10-19 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_account_isverified_alter_account_phone'),
        ('api', '0006_lesson_file_lesson_video_alter_account_phone'),
    ]

    operations = [
    ]
