# Generated by Django 5.1.1 on 2024-10-19 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_merge_20241019_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='accounts', to='api.course'),
        ),
    ]
