# Generated by Django 5.1.1 on 2024-11-07 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_account_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='biography',
        ),
    ]
