# Generated by Django 5.1.1 on 2024-11-25 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_lesson_file_course_cover_image_lesson_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='created_on',
        ),
    ]
