# Generated by Django 5.1.1 on 2024-12-26 21:10

import custom_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_lesson_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, storage=custom_storage.PublicMediaStorage, upload_to='api/upload_images'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=custom_storage.PrivateMediaStorage(), upload_to='api/upload_images/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(blank=True, null=True, storage=custom_storage.PrivateMediaStorage(), upload_to='api/upload_videos/'),
        ),
    ]
